-- Init script for PostgreSQL users table and mock data
-- Schema aligns with existing constraints in this SQL file
CREATE TABLE
    IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        firstname VARCHAR(100) NOT NULL,
        lastname VARCHAR(100) NOT NULL,
        pseudonym VARCHAR(100) NOT NULL UNIQUE,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        roles VARCHAR(100) NOT NULL DEFAULT 'user',
        birthdate DATE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_login TIMESTAMP NULL
    );

-- -- Seed users. Use ON CONFLICT to keep script idempotent.
-- INSERT INTO
--     users (
--         firstname,
--         lastname,
--         pseudonym,
--         email,
--         password,
--         roles,
--         birthdate
--     )
-- VALUES
--     (
--         'Admin',
--         'User',
--         'admin',
--         'admin@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'admin',
--         '1970-01-01'
--     ),
--     (
--         'Alice',
--         'Martin',
--         'alice',
--         'alice@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1995-04-12'
--     ),
--     (
--         'Bob',
--         'Durand',
--         'bob',
--         'bob@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1992-09-23'
--     ),
--     (
--         'Charlie',
--         'Leroy',
--         'charlie',
--         'charlie@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'coach',
--         '1988-02-05'
--     ),
--     (
--         'David',
--         'Bernard',
--         'david',
--         'david@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1991-03-14'
--     ),
--     (
--         'Emma',
--         'Petit',
--         'emma',
--         'emma@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1996-07-22'
--     ),
--     (
--         'Felix',
--         'Moreau',
--         'felix',
--         'felix@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1993-11-09'
--     ),
--     (
--         'Gabrielle',
--         'Robert',
--         'gabrielle',
--         'gabrielle@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'coach',
--         '1990-01-27'
--     ),
--     (
--         'Hugo',
--         'Richard',
--         'hugo',
--         'hugo@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1998-05-03'
--     ),
--     (
--         'Ines',
--         'Simon',
--         'ines',
--         'ines@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1997-02-18'
--     ),
--     (
--         'Jules',
--         'Michel',
--         'jules',
--         'jules@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1994-10-30'
--     ),
--     (
--         'Kim',
--         'Garcia',
--         'kim',
--         'kim@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1992-06-08'
--     ),
--     (
--         'Leo',
--         'Lopez',
--         'leo',
--         'leo@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1999-12-12'
--     ),
--     (
--         'Mila',
--         'Martinot',
--         'mila',
--         'mila@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1995-09-01'
--     ),
--     (
--         'Noah',
--         'Blanc',
--         'noah',
--         'noah@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '2000-04-25'
--     ),
--     (
--         'Olivia',
--         'Moulin',
--         'olivia',
--         'olivia@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'coach',
--         '1991-08-17'
--     ),
--     (
--         'Paul',
--         'Fontaine',
--         'paul',
--         'paul@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1993-03-06'
--     ),
--     (
--         'Quentin',
--         'Roussel',
--         'quentin',
--         'quentin@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1996-01-11'
--     ),
--     (
--         'Rose',
--         'Guerin',
--         'rose',
--         'rose@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1994-07-29'
--     ),
--     (
--         'Sarah',
--         'Martel',
--         'sarah',
--         'sarah@example.com',
--         '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZag0u.JxQ2c/8h4c7p6s9d1Y4Z5eW',
--         'user',
--         '1992-10-02'
--     ) ON CONFLICT (email) DO NOTHING;
-- -- Optionally set a last_login for admin
-- UPDATE users
-- SET
--     last_login = NOW ()
-- WHERE
--     email = 'admin@example.com'
--     AND last_login IS NULL;